In [1]:
import tensorflow as tf
import numpy as np

tf.enable_eager_execution()

In [2]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [3]:
X = np.array([h, e, l, l], dtype=np.float32)
X

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]], dtype=float32)

In [4]:
Wxh = tf.Variable([
					[0.1, 0.5, 0.9, 1.3],
					[0.2, 0.6, 1.0, 1.4],
					[0.3, 0.7, 1.1, 1.5],
					[0.4, 0.8, 1.2, 1.6]
				], dtype='float32')
Wxh

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[0.1, 0.5, 0.9, 1.3],
       [0.2, 0.6, 1. , 1.4],
       [0.3, 0.7, 1.1, 1.5],
       [0.4, 0.8, 1.2, 1.6]], dtype=float32)>

In [5]:
b = tf.Variable([0.01, 0.02, 0.03, 0.04], dtype='float32')
b

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0.01, 0.02, 0.03, 0.04], dtype=float32)>

In [6]:
Whh = tf.Variable([
					[0.1],
					[0.1],
					[0.1],
					[0.1]
				], dtype='float32')
Whh

<tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[0.1],
       [0.1],
       [0.1],
       [0.1]], dtype=float32)>

In [7]:
X[0:1]

array([[1., 0., 0., 0.]], dtype=float32)

In [8]:
h0 = tf.matmul(X[0:1], Wxh) + b
h0

<tf.Tensor: id=32, shape=(1, 4), dtype=float32, numpy=array([[0.11      , 0.52      , 0.92999995, 1.3399999 ]], dtype=float32)>

In [9]:
h0 = tf.tanh(h0)
h0

<tf.Tensor: id=33, shape=(1, 4), dtype=float32, numpy=array([[0.10955846, 0.4777    , 0.7305939 , 0.8716722 ]], dtype=float32)>

In [10]:
X[1:2]

array([[0., 1., 0., 0.]], dtype=float32)

In [11]:
h1 = tf.matmul(X[1:2], Wxh) + b
h1

<tf.Tensor: id=38, shape=(1, 4), dtype=float32, numpy=array([[0.21000001, 0.62      , 1.03      , 1.4399999 ]], dtype=float32)>

In [15]:
# 원래는 Whh를 4줄 4칸의 1미만 랜덤함 값으로 선언해서
# 결과가 4칸으로 출력되어야 한다.
tf.matmul(h0, Whh)

<tf.Tensor: id=44, shape=(1, 1), dtype=float32, numpy=array([[0.21895248]], dtype=float32)>

In [12]:
h1 = h1 + tf.matmul(h0, Whh)
h1

<tf.Tensor: id=41, shape=(1, 4), dtype=float32, numpy=array([[0.4289525, 0.8389525, 1.2489524, 1.6589525]], dtype=float32)>

In [13]:
h1 = tf.tanh(h1)
h1

<tf.Tensor: id=42, shape=(1, 4), dtype=float32, numpy=array([[0.4044455, 0.6852539, 0.8479896, 0.9300759]], dtype=float32)>