In [1]:
import tensorflow as tf
from tensorflow.nn import relu
import numpy as np

tf.enable_eager_execution()

In [2]:
# 입력값
X = np.array([
				[0, 0],
				[1, 0],
				[1, 1],
				[0, 0],
				[0, 1]
			], dtype='float32')
# 출력값
y = np.array([
				[1, 0, 0],
				[0, 1, 0],
				[0, 0, 1],
				[1, 0, 0],
				[0, 0, 1]
			], dtype='float32')

In [3]:
# w, b를 초기화 시키는 객체
initializer = tf.contrib.layers.xavier_initializer()

# 처음 선형회귀를 진행할 가중치, 바이어스
w0 = tf.Variable(initializer([2, 10]))
b0 = tf.Variable(initializer([10]))
w0, b0

(<tf.Variable 'Variable:0' shape=(2, 10) dtype=float32, numpy=
 array([[ 0.02461225, -0.36630973, -0.23273826,  0.4755599 , -0.6806591 ,
         -0.2524168 ,  0.47233754,  0.08816415, -0.26130673,  0.22199535],
        [-0.16415727, -0.64523435, -0.60856307, -0.5922625 ,  0.6191004 ,
         -0.39162344,  0.58928233, -0.2473853 , -0.6134325 ,  0.03207612]],
       dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=
 array([ 0.43602437, -0.05667317,  0.12064552, -0.40732682,  0.15524602,
         0.11569679,  0.20303667, -0.15308651, -0.4599263 , -0.03690201],
       dtype=float32)>)

In [4]:
# 2번째 선형회귀를 진행할 가중치, 바이어스
w1 = tf.Variable(initializer([10, 3]))
b1 = tf.Variable(initializer([3]))
w1, b1

(<tf.Variable 'Variable:0' shape=(10, 3) dtype=float32, numpy=
 array([[ 0.31811213,  0.37817585,  0.14799762],
        [-0.1356737 ,  0.05890721, -0.26904434],
        [ 0.14634341, -0.2911327 , -0.59477717],
        [-0.50866055, -0.3962266 , -0.6705215 ],
        [-0.46252027, -0.23437455, -0.3497373 ],
        [-0.22534227, -0.1366328 , -0.3100902 ],
        [ 0.327371  ,  0.56837213,  0.01121145],
        [-0.5717575 ,  0.07003039,  0.3636533 ],
        [ 0.42997217, -0.1560278 , -0.31243205],
        [ 0.00805771, -0.3661002 , -0.07114232]], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([ 0.9290333 , -0.15856409, -0.25831246], dtype=float32)>)

In [9]:
# 처음 예측값
hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
hypothesis0

<tf.Tensor: id=86, shape=(5, 10), dtype=float32, numpy=
array([[0.6073113 , 0.4858355 , 0.53012484, 0.3995533 , 0.5387337 ,
        0.528892  , 0.5505855 , 0.46180293, 0.3870033 , 0.49077556],
       [0.6131652 , 0.39580318, 0.4720061 , 0.51705164, 0.37158737,
        0.46587315, 0.6627055 , 0.4837751 , 0.32712153, 0.5461417 ],
       [0.57358164, 0.25574225, 0.3272486 , 0.3719105 , 0.5234047 ,
        0.37090337, 0.77982664, 0.42255157, 0.20838872, 0.55408   ],
       [0.6073113 , 0.4858355 , 0.53012484, 0.3995533 , 0.5387337 ,
        0.528892  , 0.5505855 , 0.46180293, 0.3870033 , 0.49077556],
       [0.5675512 , 0.33138946, 0.38038427, 0.26902217, 0.68446034,
        0.4314527 , 0.68832904, 0.40119898, 0.25476485, 0.49879354]],
      dtype=float32)>

In [25]:
# 선형회귀를 한 번 진행한 후 예측값
# 다중분류를 위해 softmax로 출력값과 비슷한 상태로 예측값을 조정
hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0, w1) + b1)
hypothesis1

<tf.Tensor: id=82318, shape=(5, 3), dtype=float32, numpy=
array([[9.9848574e-01, 5.9531140e-04, 9.1897085e-04],
       [1.1900330e-03, 9.9765670e-01, 1.1532662e-03],
       [9.6815362e-05, 1.4407472e-03, 9.9846244e-01],
       [9.9848574e-01, 5.9531140e-04, 9.1897085e-04],
       [1.4697944e-03, 1.6827886e-04, 9.9836189e-01]], dtype=float32)>

In [12]:
# cost(error)값
cost = -tf.reduce_sum(y * tf.log(hypothesis1)) / len(hypothesis1)
cost

<tf.Tensor: id=106, shape=(), dtype=float32, numpy=1.3055093>

In [13]:
# learning_rate 설정
optimizer = tf.train.AdamOptimizer(0.01)

In [14]:
# 반복해서 가중치와 바이어스를 찾음
for step in range(1001) :
	with tf.GradientTape() as tape :
		hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
		hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0, w1) + b1)
		cost = -tf.reduce_sum(y * tf.log(hypothesis1)) / len(hypothesis1)
		grads = tape.gradient(cost, [w0, w1, b0, b1])

	optimizer.apply_gradients(grads_and_vars=zip(grads, [w0, w1, b0, b1]))

	if step % 100 == 0 :
		print('=' * 100)
		print(f'step : {step}, cost : {cost}')
		print('=' * 100)

step : 0, cost : 1.305509328842163
step : 100, cost : 0.3392734229564667
step : 200, cost : 0.053368497639894485
step : 300, cost : 0.02005920745432377
step : 400, cost : 0.010715581476688385
step : 500, cost : 0.006749927997589111
step : 600, cost : 0.0046759494580328465
step : 700, cost : 0.0034454576671123505
step : 800, cost : 0.00265100272372365
step : 900, cost : 0.002105850027874112
step : 1000, cost : 0.0017142953583970666


In [15]:
# 반복해서 찾은 초기 가중치, 바이어스 값
w0, b0

(<tf.Variable 'Variable:0' shape=(2, 10) dtype=float32, numpy=
 array([[ 2.9707057 ,  0.23873664, -2.5015192 ,  2.4546442 , -0.15090196,
          3.250659  ,  2.9489524 ,  1.6025429 , -2.6712215 , -1.8154261 ],
        [ 2.086353  , -3.5698898 , -2.597723  , -3.2862544 ,  3.279412  ,
         -3.2075777 ,  2.0684907 ,  1.477022  , -2.865453  ,  2.6038792 ]],
       dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=
 array([-1.2282776 ,  1.533389  ,  1.2356585 , -0.86375564, -1.3863659 ,
        -1.6432124 , -1.2076733 , -0.78355396,  1.2585638 ,  0.4575229 ],
       dtype=float32)>)

In [16]:
# 반복해서 찾은 선형회귀 후 가중치, 바이어스 값
w1, b1

(<tf.Variable 'Variable:0' shape=(10, 3) dtype=float32, numpy=
 array([[-0.8564693 ,  1.1652223 ,  0.94674987],
        [ 1.4422277 ,  2.230977  , -2.1405947 ],
        [ 1.9078342 , -2.3289065 , -2.0220273 ],
        [-1.0911971 ,  1.9933021 , -2.1599028 ],
        [-1.7220054 , -2.1430786 ,  1.2579705 ],
        [-0.70161784,  2.73037   , -1.0022678 ],
        [-0.9769744 ,  1.6510643 ,  0.97361714],
        [-2.0424678 ,  0.06764359,  1.695198  ],
        [ 2.472559  , -2.6019893 , -2.0252407 ],
        [-0.22153035, -3.0776372 ,  1.3608383 ]], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([ 0.8294297 , -1.3713189 ,  0.10462492], dtype=float32)>)

In [18]:
# 반복해서 찾은 가중치와 바이어스를 통해 얻은 예측값
hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
predict = tf.nn.softmax(tf.matmul(hypothesis0, w1) + b1)
predict

<tf.Tensor: id=82300, shape=(5, 3), dtype=float32, numpy=
array([[9.9848574e-01, 5.9531140e-04, 9.1897085e-04],
       [1.1900330e-03, 9.9765670e-01, 1.1532662e-03],
       [9.6815362e-05, 1.4407472e-03, 9.9846244e-01],
       [9.9848574e-01, 5.9531140e-04, 9.1897085e-04],
       [1.4697944e-03, 1.6827886e-04, 9.9836189e-01]], dtype=float32)>

In [19]:
# 예측값 검증을 위한 transform
# argmax(numpy_array, axis) -> 각 axis에서 최대값의 index를 반환
predict01 = tf.argmax(predict, 1)
predict01

<tf.Tensor: id=82302, shape=(5,), dtype=int64, numpy=array([0, 1, 2, 0, 2], dtype=int64)>

In [20]:
# 검증 때 사용할 출력값 transform
target = tf.argmax(y, 1)
target

<tf.Tensor: id=82305, shape=(5,), dtype=int64, numpy=array([0, 1, 2, 0, 2], dtype=int64)>

In [21]:
# 예측값과 출력값 검증
ac01 = tf.equal(predict01, target)
ac01

<tf.Tensor: id=82306, shape=(5,), dtype=bool, numpy=array([ True,  True,  True,  True,  True])>

In [22]:
# 검증된 값 형변환
ac02 = tf.cast(ac01, dtype='float32')
ac02

<tf.Tensor: id=82307, shape=(5,), dtype=float32, numpy=array([1., 1., 1., 1., 1.], dtype=float32)>

In [23]:
# 정확도
ac03 = tf.reduce_mean(ac02)
ac03

<tf.Tensor: id=82309, shape=(), dtype=float32, numpy=1.0>

In [24]:
# 검증 형변환 밑 검증을 마친 후 현재 model의 정확도 계산
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, target), dtype=tf.float32))
print('=' * 50)
print('accuracy')
print(accuracy.numpy())

accuracy
1.0
